:concurrency: 1  # 並列実行数（必要に応じて増減可）

:queues:
  - default

:redis:
  url: redis://rails-redis-railway:6379/0

:scheduler:
  enabled: true
  dynamic: true
  schedule:
    active_storage_clean_job:
      cron: "0 2 * * *"  # 毎日午前2時（UTC基準）
      class: "ActiveStorageCleanJob"
      queue: default
      description: "毎日2:00に未使用のActiveStorageファイルを削除"
    daily_report_job:
      cron: "30 17 * * *"  # 毎朝7時
      class: DailyReportJob
      queue: default
      description: "毎日3:00にアクティブユーザー数などを集計"
    # compress_videos:
    #   cron: "0 2 * * *"  # 毎日午前2時（同じ時間）
    #   class: "CompressUncompressedVideosJob"
    #   queue: default
    #   description: "毎日2:00に未圧縮の動画を処理"

